### Numpy

NumPy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [5]:
import numpy as np

## create array using numpy
## Create a 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)#Shows single dimensions

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [12]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)#Output 2 braces hence 2D 

array([[1, 2, 3, 4, 5]])

In [13]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [17]:
# 2D arrays
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [ ]:
#Inbuilt Functions

np.arange(0,10,2).reshape(5,1) 

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [22]:
np.ones((3,4))#Create 2D Arrays having every element 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
## Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  # Output: (2, 3)
print("Number of dimensions:", arr.ndim)  # Output: 2
print("Size (number of elements):", arr.size)  # Output: 6
print("Data type:", arr.dtype)  # Output: int32 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize)  # Output: 8 (may vary based on platform)


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [27]:
### Numpy Vectorized Operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element Wise addition
print("Addition:", arr1+arr2)

### Element Wise Substraction
print("Substraction:", arr1-arr2)

### Other arithmetic operations....

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]


In [29]:
## Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

##Exponential
print(np.exp(arr))

##Sine
print(np.sin(arr))

## Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [32]:
## array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(arr[0][0])

1
[[3 4]
 [7 8]]


In [37]:
arr[1:] #For rows

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [43]:
print(arr[0:2, 2:]) #arr[row, column]

[[3 4]
 [7 8]]


In [45]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [47]:
## Modify array elements
arr[0,0]=100
print(arr) # number at index modified to 100

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [49]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [50]:
### Practical Applications

## Statistical concepts-- Noramlization
## to have a mean of 0 and standard deviation of 1

data =np.array([1,2,3,4,5])

#Calculate the mean and standard deviation
mean=np.mean(data)
std_div=np.std(data)

#Normalize the data
normalized_data=(data-mean)/std_div
print("Noramalized data:", normalized_data)

Noramalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [52]:
median=np.median(data)
variance=np.var(data)
print(median, variance)

3.0 2.0


In [60]:
## Logical Operation
data=np.array([1,2,3,4,5,6])

print(data[(data>5) & (data<8)])


[6]
